services:
  openssl-server-3.5.1:
    image: rub-nds/quic/openssl-server:3.5.1
    build:
      context: .
      dockerfile: Dockerfile
      target: openssl-server
      args:
        VERSION: "3.5.1"
  openssl-client-3.5.1:
    image: rub-nds/quic/openssl-client:3.5.1
    build:
      context: .
      dockerfile: Dockerfile
      target: openssl-client
      args:
        VERSION: "3.5.1"
  openssl-server-3.6.0:
    image: rub-nds/quic/openssl-server:3.6.0
    build:
      context: .
      dockerfile: Dockerfile
      target: openssl-server
      args:
        VERSION: "3.6.0"
  openssl-client-3.6.0:
    image: rub-nds/quic/openssl-client:3.6.0
    build:
      context: .
      dockerfile: Dockerfile
      target: openssl-client
      args:
        VERSION: "3.6.0"
  openssl-server-4.0.0:
    image: rub-nds/quic/openssl-server:4.0.0
    build:
      context: .
      dockerfile: Dockerfile
      target: openssl-server
      args:
        VERSION: "4.0.0"
  openssl-client-4.0.0:
    image: rub-nds/quic/openssl-client:4.0.0
    build:
      context: .
      dockerfile: Dockerfile
      target: openssl-client
      args:
        VERSION: "4.0.0"