FROM rub-nds/quic/alpine-build:3.23.3 AS xquic-base

ARG VERSION_XQUIC
ARG VERSION_BORINGSSL

# Clone projects
RUN git clone --depth=1 --branch=v${VERSION_XQUIC} https://github.com/alibaba/xquic
RUN git clone --depth 1 --branch=${VERSION_BORINGSSL} https://github.com/google/boringssl.git xquic/third_party/boringssl

# Build boringssl
WORKDIR /xquic/third_party/boringssl/
RUN cmake -B build -DCMAKE_POSITION_INDEPENDENT_CODE=ON
RUN make -C build

# Build xquic
WORKDIR /xquic/
RUN git submodule update --init --recursive
RUN mkdir -p build
WORKDIR /xquic/build/
RUN cmake -DGCOV=on -DCMAKE_BUILD_TYPE=Debug -DXQC_ENABLE_TESTING=1 -DXQC_SUPPORT_SENDMMSG_BUILD=1 -DXQC_ENABLE_EVENT_LOG=1 -DXQC_ENABLE_BBR2=1 -DXQC_ENABLE_RENO=1 -DSSL_TYPE=boringssl -DSSL_PATH=/xquic/third_party/boringssl/ ..
RUN make -j

# Add a self-signed certificate for the server
WORKDIR /xquic/build/demo/
RUN openssl req -newkey rsa:2048 -nodes -keyout server.key -x509 -days 3650 -out server.crt -subj "/CN=server.example.org"

FROM xquic-base AS xquic-server
ENTRYPOINT [ "./demo_server"]

FROM xquic-base AS xquic-client
ENTRYPOINT [ "./demo_client"]