services:
  msquic:
    build:
      context: ./msquic
      args:
        VERSION: "2.4.7"
    ports:
      - "8001:4567/udp"
    tty: true
  
  quiche-cloudflare:
    build:
      context: ./quiche-cloudflare
      args:
        VERSION: "0.23.2"
    ports:
      - "8002:8443/udp"

  mvfst:
    build:
      context: ./proxygen-mvfst
      args:
        VERSION: "2025.02.10.00"
    ports:
      - "8003:6666/udp"
  
  ngtcp2:
    build:
      context: ./ngtcp2
      args:
        VERSION: "1.10.0"
    ports:
      - "8004:8443/udp"
  
  s2n-quic:
    build:
      context: ./s2n-quic
      args:
        VERSION: "1.52.1"
    ports:
      - "8005:4433/udp"
  
  aioquic:
    build:
      context: ./aioquic
      args:
        VERSION: "1.2.0"
    ports:
      - "8006:8443/udp"
  
  xquic:
    build:
      context: ./xquic
      args:
        VERSION: "1.8.2"
    ports:
      - "8007:8443/udp"
    command: ["-r", "-l", "d"]

  picoquic:
    build:
      context: ./picoquic
    ports:
      - "8008:8443/udp"
