services:
  alpine-build-3.23.3:
    image: rub-nds/quic/alpine-build:3.23.3
    build:
      context: .
      dockerfile: Dockerfile
      args: 
        VERSION: 3.23.3
    deploy:
      replicas: 0
