ARG VERSION=3.19
FROM alpine:$VERSION

RUN apk update
RUN apk add git openssl-dev python3-dev bsd-compat-headers libffi-dev build-base py3-setuptools py3-wheel py3-wsproto py3-starlette py3-jinja2 cargo cmake go g++ clang perl libevent cunit clang lld musl-dev maven openjdk17 gradle apt bash gyp zlib-dev llvm-dev boost-dev m4