ARG VERSION=3.19

FROM alpine:$VERSION

RUN apk update
RUN apk add \
    git \
    openssl-dev \
    openssl \
    python3-dev \
    bsd-compat-headers \
    libffi-dev \
    build-base \
    py3-setuptools \
    py3-wheel \
    py3-wsproto \
    py3-starlette \
    py3-jinja2 \
    cargo \
    cmake \
    go \
    g++ \
    clang \
    perl \
    libevent-dev \
    cunit \
    lld \
    musl-dev \
    maven \
    openjdk17 \
    gradle \
    apt \
    bash \
    gyp \
    zlib-dev \
    zlib-static \
    llvm-dev \
    boost-dev \
    m4 \
    automake \
    autoconf \
    libtool \
    net-tools \
    nss-dev \
    clang-dev \
    sudo \
    glog-dev \
    double-conversion-dev \
    py3-httpbin \
    py3-asgiref \
    libev \
    libev-dev \
    shared-mime-info