services:
  quiche-cloudflare-server-0.24.5:
    image: rub-nds/quic/quiche-cloudflare-server:0.24.5
    build:
      context: .
      dockerfile: Dockerfile
      target: quiche-cloudflare-server
      args:
        VERSION: "0.24.5"
  quiche-cloudflare-client-0.24.5:
    image: rub-nds/quic/quiche-cloudflare-client:0.24.5
    build:
      context: .
      dockerfile: Dockerfile
      target: quiche-cloudflare-client
      args:
        VERSION: "0.24.5"
