services:
  quiche-cloudflare-server-0.20.0:
    image: rub-nds/quic/quiche-cloudflare-server:0.20.0
    build:
      context: .
      dockerfile: Dockerfile
      target: quiche-cloudflare-server
      args:
        VERSION: "0.20.0"
  quiche-cloudflare-client-0.20.0:
    image: rub-nds/quic/quiche-cloudflare-client:0.20.0
    build:
      context: .
      dockerfile: Dockerfile
      target: quiche-cloudflare-client
      args:
        VERSION: "0.20.0"
  quiche-cloudflare-server-0.20.1:
    image: rub-nds/quic/quiche-cloudflare-server:0.20.1
    build:
      context: .
      dockerfile: Dockerfile
      target: quiche-cloudflare-server
      args:
        VERSION: "0.20.1"
  quiche-cloudflare-client-0.20.1:
    image: rub-nds/quic/quiche-cloudflare-client:0.20.1
    build:
      context: .
      dockerfile: Dockerfile
      target: quiche-cloudflare-client
      args:
        VERSION: "0.20.1"
  quiche-cloudflare-server-0.29.0:
    image: rub-nds/quic/quiche-cloudflare-server:0.29.0
    build:
      context: .
      dockerfile: Dockerfile
      target: quiche-cloudflare-server
      args:
        VERSION: "0.29.0"
  quiche-cloudflare-client-0.29.0:
    image: rub-nds/quic/quiche-cloudflare-client:0.29.0
    build:
      context: .
      dockerfile: Dockerfile
      target: quiche-cloudflare-client
      args:
        VERSION: "0.29.0"